config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'groups#index'
  resources :users, only: :update
  resources :groups, except: %i(index destroy show) do
    resources :messages, only: %i(index create)
    collection do
      post :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members
  has_many :messages
  has_many :users, through: :members, dependent: :destroy

  validates_presence_of :name
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  default_scope -> {order('created_at ASC')}
  validates_presence_of :text
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  has_many :messages
  has_many :members
  has_many :groups, through: :members, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find(params[:id])
    @belonged_user = @group.users
    @users = @group.users
  end

  def index
    @message = Message.new
    @groups = current_user.groups
  end

  def create
    group = Group.new(group_params)
    # validationの結果による動作の条件分岐
    # クリア->
        # member_params[:user_id]の中身があるときだけ保存
    # 失敗->エラーメッセージとともにリダイレクト
    if group.save
      redirect_to :root
    else
      @group = Group.new
      @error_group = group
      render 'new'
    end
  end

  def update
    group = Group.find(params[:id])
    group.update(group_params)
    if group.valid?
      redirect_to :root
    else
      redirect_to :new_group_path
    end
  end

  def search
    @users = User.where('name LIKE(?)', "%#{params[:input]}%")
    respond_to do |format|
        format.json
    end
  end


private
  def group_params
    params.require(:group).permit(:name, {:user_ids => []})
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @groups = current_user.groups
    @group = Group.find(params[:group_id])
    @message = Message.new
    @messages = @group.messages.order('created_at DESC')
    respond_to do |format|
      format.json
      format.html
    end
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
        format.html { redirect_to group_messages_path(message_params[:group_id]) }
      end
    else
      redirect_to group_messages_path(message_params[:group_id]), :alert => "テキストを入力してください"
    end
  end

  def message_params
    params.require(:message).permit(:text).merge(user_id: current_user.id, group_id: params[:group_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update
    user = User.find(current_user.id)
    user.update(user_params)

    unless user.valid?
      redirect_to :edit_user_registration, :alert => "更新に失敗しました。入力しなおしてください"
    else
      redirect_to :root , :notice => "アカウントの更新が完了しました。"
    end

  end

private
  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_group.html.haml
.groupbox
  .groupbox__name
    = link_to "#{group.name}", group_messages_path(group.id), class: "groupbox__name--size-15"
  .groupbox__message
    - if group.messages.last
      = link_to "#{group.messages.last.text}", group_messages_path(group.id), class: "groupbox__message--size-11"
    - else
      = link_to "", group_messages_path(group.id), class: "groupbox__message--size-11"

app/views/groups/_users.html.haml
%div{:class => "chat-group-user user__id-#{users.id}"}
  .chat-group-user__name
    = users.name
  .chat-group-user__btn
    %span{:class => 'chat-group-user__btn--remove' ,:data_userid => users.id}
      削除
  %input{type: :hidden, name: :'group[user_ids][]', value: users.id}

app/views/groups/edit.html.haml
.chat-group-form
  %h1
    チャットグループ編集
  = form_for(@group) do |f|
    - if @error_group.present?
      .chat-group-form__errors
        %h2
          #{@error_group.errors.full_messages.length} 件のエラーが発生しました
        %ul
          %li
            - @error_group.errors.full_messages.each  do |error|
              = error
    .chat-group-form__field
      .chat-group-form__field--left
        = f.label :グループ名, class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, placeholder: "グループ名を入力してください", class: "chat-group-form__input"
    .chat-group-form__field
      .chat-group-form__field--left
        = f.label :チャットメンバーを追加, class: "chat-group-form__label"
      .chat-group-form__field--right
        .chat-group-form__search
          %input{type: :text, class: "chat-group-form__input", placeholder: "追加したいユーザー名を入力してください"}

    .chat-group-form__field
      .chat-group-form__field--left
        = f.label :チャットメンバー, class: "chat-group-form__label"
      .chat-group-form__field--right.choiced
        = render partial:"users", collection: @users

    .chat-group-form__field
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit :Save, class: "chat-group-form__action-btn"

app/views/groups/index.html.haml
.top
  .homeBar
    .namebox
      %span.namebox__name
        = current_user.name
        .namebox__icons
          = link_to new_group_path do
            %i.fa.fa-pencil-square-o.namebox__icons--pen
          = link_to edit_user_registration_path do
            %i.fa.fa-cog.namebox__icons--gear
  .topBar__index

.main
  .side
    .groupArea
      = render partial:"group", collection: @groups

  .content__index

app/views/groups/new.html.haml
.chat-group-form
  %h1
    新規のチャットグループ
  = form_for(@group) do |f|
    - if @error_group.present?
      .chat-group-form__errors
        %h2
          #{@error_group.errors.full_messages.length} 件のエラーが発生しました
        %ul
          %li
            - @error_group.errors.full_messages.each  do |error|
              = error
    .chat-group-form__field
      .chat-group-form__field--left
        = f.label :グループ, class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, placeholder: "グループ名を入力してください", class: "chat-group-form__input"
    .chat-group-form__field
      .chat-group-form__field--left
        = f.label :チャットメンバーを追加, class: "chat-group-form__label"
      .chat-group-form__field--right
        .chat-group-form__search
          %input{type: :text, class: "chat-group-form__input", placeholder: "追加したいユーザー名を入力してください"}

    .chat-group-form__field
      .chat-group-form__field--left
        = f.label :チャットメンバー, class: "chat-group-form__label"
      .chat-group-form__field--right.choiced
        .chat-group-user

    .chat-group-form__field
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit :Save, class: "chat-group-form__action-btn"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    -if notice
      %p.flashbox--color-blue
        =flash[:notice]
    -if alert
      %p.flashbox--color-red
        =flash[:alert]
    =yield

app/views/messages/_group.html.haml
.groupbox
  .groupbox__name
    = link_to "#{group.name}", group_messages_path(group.id), class: "groupbox__name--size-15"
  .groupbox__message
    - if group.messages.last
      = link_to "#{group.messages.last.text}", group_messages_path(group.id), class: "groupbox__message--size-11"
    - else
      = link_to "", group_messages_path(group.id), class: "groupbox__message--size-11"

app/views/messages/_message.html.haml
%div{:class => "chatbox" ,:data_messageid => "#{message.id}"}
  .chatbox__data
    %span.chatbox__data__name
      = message.user.name
    %span.chatbox__data__date
      = message.created_at.strftime("%Y-%m-%d %H:%M:%S")
  .chatbox__gap
  .chatbox__chat
    %span.chatbox__message
      = message.text

app/views/messages/index.html.haml
.top
  .homeBar
    .namebox
      %span.namebox__name
        = current_user.name
        .namebox__icons
          = link_to new_group_path do
            %i.fa.fa-pencil-square-o.namebox__icons--pen
          = link_to edit_user_registration_path do
            %i.fa.fa-cog.namebox__icons--gear

  .topBar
    .topbox
      .titlebox
        .titlebox__groupbox
          %span.titlebox__groupname
            = @group.name
        .titlebox__memberbox
          %span.titlebox__membername
            member :
            - @group.users.each do |user|
              = user.name

      .editbox
        = link_to "Edit", edit_group_path(@group.id), class: "editbox__button"

.main
  .side
    .groupArea
      = render partial: "group", collection: @groups

  .content
    .chatArea
      .chatgap
      = render partial: "message", collection: @messages

    .inputArea
      .inputbox
        = form_for @message, :url => group_messages_path(@group) do |f|
          .inputbox__chat
            .inputbox__messagebox
              = f.text_field :text, class: "inputbox__message", placeholder: "  type a message"
            .inputbox__filebox
              = f.label :image, for: "file-input" do
                %i.fa.fa-picture-o
              = f.file_field :image, id: "file-input", style: "display:none";
          .inputbox__gap
          = f.submit 'Send', class: "inputbox__button"